blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed


app_name='blog'

urlpatterns = [

    path ('',blog_view,name='index'),
    path ('<int:pid>',blog_single,name='single'),
    path ('author/<str:author_username>',blog_view,name='author'),
    path ('category/<str:cat_name>',blog_view,name='category'),
    path ('tag/<str:tag_name>',blog_view,name='tag'),
    path ('search/',blog_search,name='search'),
    path('rss/feed/', LatestEntriesFeed()),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from mysite.settings import STATIC_URL
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps={
    'static':StaticViewSitemap,
    'blog':BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path ('accounts/', include('accounts.urls')),
    path ('accounts/', include('django.contrib.auth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name='website'

urlpatterns = [

    path ('',Home_page_view,name='index'),
    path ('category/<str:cat_name>',Home_page_view,name='category'),
    path ('tag/<str:tag_name>',Home_page_view,name='tag'),
    path ('about/',about_view,name='about'),
    path ('contact/',contact_view,name='contact'),
  
]

templates/website_temp/about.html
{%extends 'base.html'%}
{% load static %}
{%block content%}


    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{%url 'website:index'%}"><h2>Stand Blog<em>.</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{%url 'website:index'%}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item active">
                <a class="nav-link" href="{%url 'website:about'%}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'blog:index'%}">Blog Entries</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href=""></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'website:contact'%}">Contact Us</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>about us</h4>
                <h2>more about us!</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->


    <section class="about-us">
      <div class="container">
      	
        <div class="row">
          <div class="col-lg-12">
            <img src="{% static 'assets/images/about-us.jpg'%}" alt="">
            <p>Please tell your friends about TemplateMo website. Thank you. You can browse through different categories of templates such as <a rel="nofollow" href="https://templatemo.com/tag/business" target="_parent">business</a>, <a rel="nofollow" href="https://templatemo.com/tag/portfolio" target="_parent">portfolio</a>, <a rel="nofollow" href="https://templatemo.com/tag/restaurant" target="_parent">restaurant</a>, etc. Pellentesque quis luctus libero. Maecenas pretium molestie erat, ac tincidunt leo gravida ac. Cras ullamcorper eu ipsum eu sollicitudin. Fusce vitae commodo turpis. Integer ullamcorper purus nec justo mollis fermentum. Nunc imperdiet erat nec lacinia laoreet. <br><br>Maecenas faucibus ullamcorper felis vitae finibus. Nullam at quam ut lacus aliquam tempor vel sed ipsum. Donec pellentesque tincidunt imperdiet. Mauris sit amet justo vulputate, cursus massa congue, vestibulum odio. Aenean elit nunc, gravida in erat sit amet, feugiat viverra leo. Phasellus interdum, diam commodo egestas rhoncus, turpis nisi consectetur nibh, in vehicula eros orci vel neque.</p>
          </div>
        </div>
        
        <div class="row">
          <div class="col-lg-6">
          <h4>Two-One Donec porttitor augue</h4>
          	<p>Quisque bibendum cursus viverra. Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum ante euismod vel. Aliquam at metus sit amet nunc dapibus posuere.</p>
          </div>
          <div class="col-lg-6">
          <h4>Two-Two Donec porttitor augue</h4>
          	<p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
        </div>
        
        <div class="row">
          <div class="col-lg-4 col-md-6">
          <h4>1-03 Donec porttitor augue</h4>
          	<p>Quisque bibendum cursus viverra. Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum ante euismod vel. Aliquam at metus sit amet nunc dapibus posuere.</p>
          </div>
          <div class="col-lg-4 col-md-6">
          <h4>2-03 Donec porttitor augue</h4>
          	<p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
          <div class="col-lg-4">
          <h4>3-03 Donec porttitor augue</h4>
          	<p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
        </div>
        
        
        <div class="row">
          <div class="col-lg-3 col-md-6">
          <h4>01 Four Columns</h4>
          	<p>Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum ante euismod vel. Aliquam at metus sit amet nunc dapibus posuere.</p>
          </div>
          <div class="col-lg-3 col-md-6">
          <h4>02 Four Columns</h4>
          	<p>Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
          <div class="col-lg-3 col-md-6">
          <h4>03 Four Columns</h4>
          	<p>Morbi ac interdum metus. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
          <div class="col-lg-3 col-md-6">
          <h4>04 Four Columns</h4>
          	<p>Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
          </div>
        </div>
        
        <div class="row">
          <div class="col-lg-12">
            <ul class="social-icons">
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-behance"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
        
        
      </div>
    </section>

    {%endblock%}

templates/website_temp/blog_lastpost.html
{% load static %}
{% load humanize %}
{% load blog_tags %}
{% for post in posts %}
<div class="item">
    <img src="{{post.image.url}}" alt="">
    <div class="item-content">
      <div class="main-content">
        <div class="meta-category">
        
          {% for cat in post.category.all %}
          <span>{{cat.name}}</span>{% if not forloop.last %},
          {% endif %} 
            
          {% endfor %}
     
        </div>
        <a href="{% url 'blog:single' pid=post.id %}"><h4>{{post.title}}</h4></a>
        <ul class="post-info">
          <li><a href="#">{{post.author.get_full_name}}</a></li>
          <li><a href="#">{{post.publish_date|date:"d M Y"}}</a></li>
          <li><a href="#">{% comments_count post.id %} Comments</a></li>
          <li><a href="#">{{post.count_views}} Views</a></li>
        </ul>
      </div>
    </div>
  </div>

  {% endfor %}

templates/website_temp/blog_lastpost_home.html
{% load static %}
{% for post in posts %}

<div class="col-lg-12">
  <div class="blog-post">
    <div class="blog-thumb">
      <img src="{{post.image.url}}" alt="">
    </div>
    <div class="down-content">
      <span>{{post.category.all|join:' , '}}</span>
      <a href="{% url 'blog:single' pid=post.id %}"><h4>B{{post.title}}</h4></a>
      <ul class="post-info">
        <li><a href="#">{{post.author.get_full_name}}</a></li>
        <li><a href="#">{{post.publish_date|date:"d M Y"}}</a></li>
        <li><a href="#">{{comments|length}} Comments</a></li>
        <li><a href="#">{{post.count_views}} Views</a></li>
      </ul>
      <p>{{post.content|safe}} <a rel="nofollow" href="#" target="_parent"></a> </p>
      <div class="post-options">
        <div class="row">
          <div class="col-6">
            <ul class="post-tags">
              {% for tag in post.tags.all %}
              <li><i class="fa fa-tags"></i></li>
              <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a>{% if not forloop.last %},</li>
              {% endif %} 

              {% endfor %}

            </ul>
          </div>
          <div class="col-6">
            <ul class="post-share">
              <li><i class="fa fa-share-alt"></i></li>
              <li><a href="#">Facebook</a>,</li>
              <li><a href="#"> Twitter</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




{% endfor %}



<div class="col-lg-12">
  <div class="main-button">
    <a href="{%url 'blog:index'%}">View All Posts</a>
  </div>
</div>

templates/website_temp/contact.html
{%extends 'base.html'%}
{% load static %}
{%block content%}

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{%url 'website:index'%}"><h2>Stand Blog<em>.</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{%url 'website:index'%}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="{%url 'website:about'%}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'blog:index'%}">Blog Entries</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href=""></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{%url 'website:contact'%}">Contact Us</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>contact us</h4>
                <h2>let’s stay in touch!</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->

    
    <section class="contact-us">
      <div class="container">
        <div class="row">
        
          <div class="col-lg-12">
            <div class="down-contact">
              <div class="row">
                <div class="col-lg-8">
                  <div class="sidebar-item contact-form">
                    <div class="sidebar-heading">
                      <h2>Send us a message</h2>
                    </div>
                    <div class="content">
                      <form action="{% url 'website:contact' %}" method="post">
                        <div class="row">
                          {% csrf_token %}
                          <div class="col-md-6 col-sm-12">
                            <fieldset>
                              <input name="name" type="text" id="name" placeholder="Your name" required="">
                            </fieldset>
                          </div>
                          <div class="col-md-6 col-sm-12">
                            <fieldset>
                              <input name="email" type="text" id="email" placeholder="Your email" required="">
                            </fieldset>
                          </div>
                          <div class="col-md-12 col-sm-12">
                            <fieldset>
                              <input name="subject" type="text" id="subject" placeholder="Subject">
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <textarea name="message" rows="6" id="message" placeholder="Your Message" required=""></textarea>
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <div class="pb-3">{{form.captcha}}</div>
                            <fieldset>
                              <button type="submit"  class="main-button">Send Message</button>
                            </fieldset>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="sidebar-item contact-information">
                    <div class="sidebar-heading">
                      <h2>contact information</h2>
                    </div>
                    <div class="content">
                      <ul>
                        <li>
                          <h5>090-484-8080</h5>
                          <span>PHONE NUMBER</span>
                        </li>
                        <li>
                          <h5>info@company.com</h5>
                          <span>EMAIL ADDRESS</span>
                        </li>
                        <li>
                          <h5>123 Aenean id posuere dui, 
                          	<br>Praesent laoreet 10660</h5>
                          <span>STREET ADDRESS</span>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% if messages %}
          <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
          </ul>
          {% endif %}

          {% if messages %}
          <ul class="messages" >
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} {% endif %}
              
            </li>
            {% endfor %}
          </ul>
          {% endif %}
    
        </div>
      </div>
    </section>

    {%endblock%}

templates/website_temp/index.html
{%extends 'base.html'%}
{% load static %}
{% load blog_tags %}
{% load home_tags %}
{% load humanize %}

{%block content%}

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{%url 'website:index'%}"><h2>Stand Blog<em>.</em></h2>
            

          
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                
                <a class="nav-link" href="{%url 'website:index'%}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="{%url 'website:about'%}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'blog:index'%}">Blog Entries</a>
              </li>
 
              <li class="nav-item">
                <a class="nav-link" href="#"></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'website:contact'%}">Contact Us</a>
              </li>
              
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="main-banner header-text">
      <div class="container-fluid">
        <div class="owl-banner owl-carousel">


          {% lastestposts %}


        </div>
      </div>
    </div>
    <!-- Banner Ends Here -->

    <section class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="main-content">
              <div class="row">
                <div class="col-lg-8">
                  <span>How Your Dreams Can Make You More Creative</span>
                  <h4>Create Your JOB</h4>
                </div>
                <div class="col-lg-4">
                  <div class="main-button">
                    <a href="#" target="_parent">DOWNLOAD APP</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


    <section class="blog-posts">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">



                {% lastestpost %}
                
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
                {% include 'blog_temp/blog_search.html' %}
                {% include 'blog_temp/blog-lastest-post.html' %}
                {% postcategories %}
                
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {%endblock%}