accounts/urls.py
from django.urls import path
from accounts.views import *

app_name='accounts'

urlpatterns = [

    path ('login/',login_view,name='login'),
    path ('logout/',logout_view,name='logout'),
    path ('signup/',signup_view,name='signup'),
]

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed


app_name='blog'

urlpatterns = [

    path ('',blog_view,name='index'),
    path ('<int:pid>',blog_single,name='single'),
    path ('author/<str:author_username>',blog_view,name='author'),
    path ('category/<str:cat_name>',blog_view,name='category'),
    path ('tag/<str:tag_name>',blog_view,name='tag'),
    path ('search/',blog_search,name='search'),
    path('rss/feed/', LatestEntriesFeed()),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from mysite.settings import STATIC_URL
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps={
    'static':StaticViewSitemap,
    'blog':BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path ('accounts/', include('accounts.urls')),
    path ('accounts/', include('django.contrib.auth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <title>Stand Blog - Contact Page</title>
    {% compress css %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-stand-blog.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css'%}">
    {% endcompress %}
<!--

TemplateMo 551 Stand Blog

https://templatemo.com/tm-551-stand-blog

-->
  </head>

  <body>
    {% if messages %}
    {% for message in messages %}
     {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}

       {% endfor %}

      {% endif %}
    <!-- ***** Preloader Start ***** -->
    
          <div class="col-lg-12">
            <div class="copyright-text">
              {% if request.user.is_authenticated %}
              <p>Login as {{request.user.username}}
             
                    
                  <a rel="nofollow" href="{% url 'accounts:logout' %}" target="_parent">Logout</a></p>
              
              {% else %}
              <a rel="" href="{% url 'accounts:login' %}" target="">Login</a>    or   
              
              <a rel="" href="{% url 'accounts:signup' %}" target="">Signup</a>
              {% endif %}
            </div>

      
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->
{%block content%}

{%endblock%}

<!-- ******foooteeer***** -->

    <footer>
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <ul class="social-icons">
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Behance</a></li>
                <li><a href="#">Linkedin</a></li>
                <li><a href="#">Dribbble</a></li>
              </ul>
            </div>
            <div class="col-lg-12">
              <div class="copyright-text">
                {% if request.user.is_authenticated %}
                <p>Login as {{request.user.username}}
                      
                   <a rel="nofollow" href="#" target="_parent"></a></p>

                <p>
                      
                     <a rel="nofollow" href="{% url 'accounts:logout' %}" target="_parent">Logout</a></p>
                <p>
                  {% else %}
                     <a rel="nofollow" href="{% url 'accounts:login' %}" target="_parent">Login</a></p>
                <p>
                       <a rel="nofollow" href="{% url 'accounts:signup' %}" target="_parent">Signup</a></p>
                {% endif %}
                <p> | Design: <a rel="nofollow" href="#" target="_parent">Mohi FK</a></p></p>
              </div>
            </div>
          </div>
        </div>
      </footer>

      {% compress js %}
  
      <!-- Bootstrap core JavaScript -->
      <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  
      <!-- Additional Scripts -->
      <script src="{% static 'assets/js/custom.js'%}"></script>
      <script src="{% static 'assets/js/owl.js'%}"></script>
      <script src="{% static 'assets/js/slick.js'%}"></script>
      <script src="{% static 'assets/js/isotope.js'%}"></script>
      <script src="{% static 'assets/js/accordions.js'%}"></script>
      {% endcompress %}
      <script language = "text/Javascript"> 
        cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
        function clearField(t){                   //declaring the array outside of the
        if(! cleared[t.id]){                      // function makes it static and global
            cleared[t.id] = 1;  // you could use true and false, but that's more typing
            t.value='';         // with more chance of typos
            t.style.color='#fff';
            }
        }
      </script>
  
    </body>
  </html>

templates/popularposts.html
<ul>

    {%  for post in posts   %}
    {% if post.id.has_next %}
    {% url 'blog:single' pid=post.id %}"
    {% endif %}
    {%  endfor  %}

</ul>