blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed


app_name='blog'

urlpatterns = [

    path ('',blog_view,name='index'),
    path ('<int:pid>',blog_single,name='single'),
    path ('author/<str:author_username>',blog_view,name='author'),
    path ('category/<str:cat_name>',blog_view,name='category'),
    path ('tag/<str:tag_name>',blog_view,name='tag'),
    path ('search/',blog_search,name='search'),
    path('rss/feed/', LatestEntriesFeed()),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from mysite.settings import STATIC_URL
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps={
    'static':StaticViewSitemap,
    'blog':BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path ('accounts/', include('accounts.urls')),
    path ('accounts/', include('django.contrib.auth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name='website'

urlpatterns = [

    path ('',Home_page_view,name='index'),
    path ('category/<str:cat_name>',Home_page_view,name='category'),
    path ('tag/<str:tag_name>',Home_page_view,name='tag'),
    path ('about/',about_view,name='about'),
    path ('contact/',contact_view,name='contact'),
  
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class category(models.Model):
    name=models.CharField(max_length=255)
    def __str__(self) -> str:
        return self.name
class Post(models.Model):
    image=models.ImageField(upload_to='media/blog/',default='blog/defult.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    title=models.CharField(max_length=255)
    content= models.TextField()
    tags=TaggableManager()
    category=models.ManyToManyField(category)
    count_views= models.IntegerField(default=0)
    status= models.BooleanField(default=False)
    login_require= models.BooleanField(default=False)
    publish_date= models.DateTimeField(null=True)
    create_date= models.DateTimeField(auto_now_add=True)
    update_date= models.DateTimeField(auto_now=True)

    class Meta :
        ordering=['create_date']
    def __str__(self):
        #return "title{} and Id{}".format(self.title,self.id)
        return '%d'%self.id
    def snippets(self):
        return self.content[:10]+'...'

    def get_absolute_url(self):
        return reverse('blog:single',kwargs={'pid':self.id})
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Mets:
        ordering=['-create_date']

blog/forms.py
from django import forms
from blog.models import Comment


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields=['post','name','subject','message','email']

blog/views.py
from blog.models import Post,Comment
from django.utils import timezone
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator , EmptyPage , PageNotAnInteger
from django.contrib import messages
from django.http import HttpResponseRedirect 
from blog.forms import CommentForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect




def blog_view(request,**kwargs):
    posts=Post.objects.filter(publish_date__lte=timezone.now(),status=1) 
    if kwargs.get('cat_name') !=None:
        posts=posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_username') !=None:
        posts=posts.filter(author__username=kwargs['author_username'])
    if kwargs.get('tag_name') !=None:
        posts=posts.filter(tags__name__in=[kwargs['tag_name']])
    posts= Paginator(posts,4)
    try:
        page_number = request.GET.get('page')
        posts=posts.get_page(page_number)
    except PageNotAnInteger :
        posts=posts.get_page(1)
    except EmptyPage:
        posts=posts.get_page(1)
    context={'posts':posts}                                
    return render(request,'blog_temp/blog-home.html',context)



def blog_single(request,pid):
    if request.method == 'POST' :
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS,'OK Dude your Comment submit SUCCESS It will be displayed after confirmation')
        else:
            messages.add_message(request,messages.ERROR,'Sorry Dude your Comment dident submit')
    posts=Post.objects.filter(status=1) 
    post_=get_object_or_404(Post,pk=pid,status=True)
    if not post_.login_require:
        post_.count_views+=1
        post_.save()        
        comments=Comment.objects.filter(post=post_.id,approved=1)  
        form= CommentForm()      
        context={'post':post_,'comments':comments,'form':form}
        return render(request,'blog_temp/blog-single.html',context)
    elif not request.user.is_authenticated :
        return HttpResponseRedirect(reverse('accounts:login'))

    elif request.user.is_authenticated:
        post_.count_views+=1
        post_.save()   
        comments=Comment.objects.filter(post=post_.id,approved=1)  
        form= CommentForm()      
        context={'post':post_,'comments':comments,'form':form}
        return render(request,'blog_temp/blog-single.html',context)


def blog_search(request):
    posts=Post.objects.filter(status=1)
    if request.method == 'GET' :
        if s:= request.GET.get('s'):
            posts=posts.filter(content__contains=s)
    context={'posts':posts}
    return render(request,'blog_temp/blog-home.html',context)

templates/blog_temp/blog-home.html
{%extends 'base.html'%}
{% load static %}
{% load blog_tags %}
{% load humanize %}

{%block content%}

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{%url 'website:index'%}"><h2>Stand Blog<em>.</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{%url 'website:index'%}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="{%url 'website:about'%}">About Us</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{%url 'blog:index'%}">Blog Entries</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#"></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'website:contact'%}">Contact Us</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>Recent Posts</h4>
                <h2>Our Recent Blog Entries</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->

    <section class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="main-content">
              <div class="row">
                <div class="col-lg-8">
                  <span>How Your Dreams Can Make You More Creative</span>
                  <h4>Create Your JOB</h4>
                </div>
                <div class="col-lg-4">
                  <div class="main-button">
                    <a href="#" target="_parent">DOWNLOAD APP</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
              {% for post in posts %}
                <div class="col-lg-6">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <a href="{%url 'blog:single' pid=post.id%}"><img src="{{post.image.url}}" alt="">
                    </div>
                    <div class="down-content">
                      {% for cat in post.category.all %}
                      <span><a href=""><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a>{% if not forloop.last %},
                        {% endif %} 
                        
                        {% endfor %}
                      </a></span>
                      <a href="{%url 'blog:single' pid=post.id%}"><h4>{{post.title}}</h4></a>
                      <ul class="post-info">
                        <li><a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a></li>
                        <li><a href="#">{{post.count_views}} Views</a></li>
                        <li><a href="#">{{post.publish_date|date:"d M Y"}}</a></li>
                        <li><a href="#">{% comments_count post.id %} Comments</a></li>
                      </ul>
                      <p>{{post.content|truncatewords:5|safe}}</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-lg-12">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              {% for tag in post.tags.all %}
                              <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a>{% if not forloop.last %},</li>
                                {% endif %}
                              {% endfor %}
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}

                <div class="col-lg-12">
                  <ul class="page-numbers">
                    
                    
                      {% if posts.has_previous %}
                      <li class="page-item">
                        <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
                            <span aria-hidden="true">
                                <span class="lnr lnr-chevron-left"></span>
                            </span>
                        </a>
                      </li>
                      {% endif %}
                      {% for i in posts.paginator.page_range %}
                      {% if posts.number == i %}
                      <li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                      {% else %}
                      <li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                      {% endif %}
                      {% endfor %}
                      {% if posts.has_next %}
                          <li class="page-item">
                              <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
                                {% endif %}
                                  <span aria-hidden="true">
                                      <span class="lnr lnr-chevron-right"></span>
                                 </span>

                              </a>
                           </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
                {% include 'blog_temp/blog_search.html' %}
                {% include 'blog_temp/blog-lastest-post.html' %}
                {% postcategories %}
               
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {%endblock%}

    

templates/blog_temp/blog-lastest-post.html
{% load static %}
{% load humanize %}
<div class="col-lg-12"></div>
  <div class="sidebar-item recent-posts">
      <div class="sidebar-heading">
        <h2>Recent Posts</h2>
      </div>
      {% for post in posts %}
      <div class="content">
        <ul>
          <li><a href="{% url 'blog:single' pid=post.id %}">
            <h5>{{post.title}}</h5>
            <span>{{post.publish_date|date:"d M Y"}}</span>
            
          </a></li>
        </ul>
      {% endfor %}
      </div>
    </div>
  </div>  

templates/blog_temp/blog-post-category.html
{% load static %}
<div class="col-lg-12"></div>
  <div class="sidebar-item categories">
      <div class="sidebar-heading">
        <h2>Categories</h2>
      </div>
      <div class="content">
        <ul>
          
      {% for name,count in categories.items %}
      <li>
        <a href="{% url 'blog:category' cat_name=name %}" class="d-flex justify-content-between">
            <p>-{{name}}</p>
            <p>{{count}}</p>
        </a>
    </li>
              
      {% endfor %}         
        </ul>
      </div>
    </div>
  </div>

templates/blog_temp/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% load humanize %}

{%block content%}

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{%url 'website:index'%}"><h2>Stand Blog<em>.</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{%url 'website:index'%}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="{%url 'website:about'%}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'blog:index'%}">Blog Entries</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="#"></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'website:contact'%}">Contact Us</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>Post Details</h4>
                <h2>Single blog post</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->

    <section class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="main-content">
              <div class="row">
                <div class="col-lg-8">
                  <span>How Your Dreams Can Make You More Creative</span>
                  <h4>Create Your JOB</h4>
                </div>
                <div class="col-lg-4">
                  <div class="main-button">
                    <a href="#" target="_parent">DOWNLOAD APP</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="{{post.image.url}}" alt="">
                    </div>
                    <div class="down-content">
                      <span>{{post.category.all|join:' , '}}</span>
                      <a href="{%url 'blog:single' pid=post.id%}"><h4>{{post.title}}</h4></a>
                      <ul class="post-info">
                        <li><a href="#">{{post.author.username}}</a></li>
                        <li><a href="#">{{post.publish_date|date:"d M Y"}}</a></li>
                        <li><a href="#">{{comments|length}} Comments</a></li>
                        <li><a href="#">{{post.count_views}} Views</a></li>
                      </ul>
                      <p>{{post.content|safe}}
                      </p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              {% for tag in post.tags.all %}
                              <li><i class="fa fa-tags"></i></li>
                              <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a>{% if not forloop.last %},</li>
                              {% endif %} 
						
                              {% endfor %}
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Facebook</a>,</li>
                              <li><a href="#"> Twitter</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item comments">
                    <div class="sidebar-heading">
                      <h2>{{comments|length}} comments</h2>
                    {% for comment in comments %}
                    </div>
                    
                    <div class="content">
                    
                      <ul>
                        <li>
                          <div class="author-thumb">
                            <img src="{% static 'assets/images/comment-author-02.jpg'%}" alt="">
                          </div>
                          <div class="right-content">
                            <h4>{{comment.name}}<span>{{comment.create_date|naturalday}}</span></h4>
                            <p>{{comment.message}}</p>
                          </div>
                        </li>
                        {% endfor %}
                                        
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item submit-comment">
                    <div class="sidebar-heading">
                      <h2>Your comment</h2>
                    </div>
                    <div class="content">
                      
                      
                      <form action='{% url "blog:single" pid=post.id %}' method="post">
                        {% csrf_token %}
                        <input type="hidden" name="post" value={{post.id}}>
                        {% if request.user.is_authenticated %}
                        <input type="hidden" name="name" value={{request.user.first_name}}>
						            <input type="hidden" name="email" value={{request.user.email}}>
                        {% else %}
                        <div class="row">
                          <div class="col-md-6 col-sm-12">
                            <fieldset>
                              <input name="name" type="text"  placeholder="Your name" required="">
                            </fieldset>
                          </div>
                          <div class="col-md-6 col-sm-12">
                            <fieldset>
                              <input name="email" type="text"  placeholder="Your email" required="">
                            </fieldset>
                          </div>
                          <div class="col-md-12 col-sm-12">
                          {% endif %}
                            <fieldset>
                              <input name="subject" type="text"  placeholder="Subject">
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <textarea name="message" rows="6"  placeholder="Type your comment" required=""></textarea>
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" class="main-button">Submit</button>
                            </fieldset>
                          </div>
                    
           </ul>
         </div>
       </div>
     </div>
   </div>
   <div class="col-lg-4">
     <div class="sidebar">
       <div class="row">

         </div>
       </div>
     </div>
   </div>
 </div>
</div>
</section>

{%endblock%}

templates/blog_temp/blog_search.html
{% load static %}
<div class="col-lg-12">
  <div class="sidebar-item search">
    <form name="s" method="get" action="{% url 'blog:search' %}">
      <input type="text" name="s" class="searchText" placeholder="type to search..." autocomplete="on">
      <!-- <button type="submit"><i class="fa fa-search"></i></button> -->
    </form>
  </div>
</div>

templates/blog_temp/blog_tag.html
{% load static %}

<div class="col-lg-12"></div>
  <div class="sidebar-item tags">
      <div class="sidebar-heading">
        <h2>Tag Clouds</h2>
      </div>
      <div class="content">
      {% for tag in post.tags.all %}
        <ul>
          <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a>{% if not forloop.last %},</li>
            {% endif %}
        {% endfor %}
        </ul>
      </div>
    </div>